drivers: bcmdhd: fix compilation process
"\" is required

fix:

kernel/sony/msm/drivers/net/wireless/bcmdhd/dhd_linux.c: In function 'dhd_preinit_ioctls':
kernel/sony/msm/drivers/net/wireless/bcmdhd/dhd_linux.c:5727:43: error: operator '||' has no right operand
^

Signed-off-by: Humberto Borba <humberos@gmail.com>
Change-Id: I599eaf1bdef66879e8d79dc7d399ece37a4b4d46