proc: uid: Adds accounting for the cputimes per uid.
Adds proc files /proc/uid_cputime/show_uid_stat and
/proc/uid_cputime/remove_uid_range.

show_uid_stat lists the total utime and stime for the active as well as
terminated processes for each of the uids.

Writing a range of uids to remove_uid_range will delete the accounting
for all the uids within that range.

Change-Id: I21d9210379da730b33ddc1a0ea663c8c9d2ac15b

Conflicts:
	drivers/misc/Kconfig
	drivers/misc/Makefile

Includes
commit 4b92e17503fca8f59732c44c6d3874ba66d25ab4
Author: Ruchi Kandoi <kandoiruchi@google.com>
Date:   Fri Jul 31 10:17:54 2015 -0700

    uid_cputime: Iterates over all the threads instead of processes.

    Bug: 22833116
    Change-Id: I775a18f61bd2f4df2bec23d01bd49421d0969f87
    Signed-off-by: Ruchi Kandoi <kandoiruchi@google.com>

commit eefab841d17e88fcd5cca7be6813499a8eb1092f
Author: Jin Qian <jinqian@google.com>
Date:   Mon Jul 13 18:16:55 2015 -0700

    uid_cputime: fix cputime overflow

    Converting cputime_t to usec caused overflow when the value is greater
    than 1 hour. Use msec and convert to unsigned long long to support bigger
    range.

    Bug: 22461683

    Change-Id: I853fe3e8e7dbf0d3e2cc5c6f9688a5a6e1f1fb3e
    Signed-off-by: Jin Qian <jinqian@google.com>

commit 22920f18b6278d506410e743ddda9cbbd65a0863
Author: Ruchi Kandoi <kandoiruchi@google.com>
Date:   Fri Jun 26 14:19:21 2015 -0700

    uid_cputime: Avoids double accounting of process stime, utime and cpu_power in
    task exit.

    This avoids the race where a particular process is terminating and we
    read the show_uid_stats. At this time since the task_struct still exists
    and we will account for the terminating process as one of the active
    task, where as the stats would have been added in the task exit
    callback.

    Bug: 22064385
    Change-Id: Id2ae04b33fcd230eda9683a41b6019d4dd8f5d85
    Signed-off-by: Jin Qian <jinqian@google.com>
    Signed-off-by: Ruchi Kandoi <kandoiruchi@google.com>

commit dcc4af2ea1715ef5ecdc8c1764dd32bffc08716b
Author: Ruchi Kandoi <kandoiruchi@google.com>
Date:   Fri Apr 17 16:52:54 2015 -0700

    uid_cputime: Extends the cputime functionality to report power per uid

    /proc/uid_cputime/show_uid_stats shows a third field power for each of
    the uids. It represents the power in the units (uAusec)

    Change-Id: I52fdc5e59647e9dc97561a26d56f462a2689ba9c
    Signed-off-by: Ruchi Kandoi <kandoiruchi@google.com>

commit 086a621d7248da13edb779d70c1a9b7d434c7afc
Author: Jin Qian <jinqian@google.com>
Date:   Mon May 11 17:57:52 2015 -0700

    proc: uid_cputime: fix show_uid_stat permission

    Change-Id: Ice9084e39da599261df0be6dc305b817b50cfbbf
    Signed-off-by: Jin Qian <jinqian@google.com>

commit d919e5b0b83fc283178484acda08ada02f339af3
Author: Amit Pundir <amit.pundir@linaro.org>
Date:   Wed Apr 15 00:40:21 2015 +0530

    proc: uid_cputime: create uids from kuids

    Create uids from kuids using from_kuid_munged(),
    otherwise we run into following build error and warnings:
    --------------------
      CC      drivers/misc/uid_cputime.o
    drivers/misc/uid_cputime.c: In function ‘uid_stat_show’:
    drivers/misc/uid_cputime.c:90:36: error: incompatible type for argument 1 of ‘find_or_register_uid’
    drivers/misc/uid_cputime.c:54:26: note: expected ‘uid_t’ but argument is of type ‘kuid_t’
    drivers/misc/uid_cputime.c:94:4: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘kuid_t’ [-Wformat]
    drivers/misc/uid_cputime.c: In function ‘process_notifier’:
    drivers/misc/uid_cputime.c:194:6: error: incompatible types when assigning to type ‘uid_t’ from type ‘kuid_t’
    make[2]: *** [drivers/misc/uid_cputime.o] Error 1
    --------------------

    Change-Id: Ifecb98001f7fe2fac74d1ef3e1abd03d43fc9059
    Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
    (cherry picked from commit b0f4decae627cf2d74e6f72c7ecb939c77d48625)